from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as uReq
code=int(input("Enter the zip code"))
if code==32746:
 my_url = "https://www.aaa.com/autorepair/locations/32746?radius=50&itemcategory=&napalocations="
 uClient = uReq(my_url)
 page_html = uClient.read()
 uClient.close()
 page_soup = soup(page_html, "html.parser")
 containers = page_soup.find_all("div", {"class":"aar-detail-wrapper"})
#print(len(containers))
 container = containers[0]
#print(soup.prettify(containers[0]))
 name=container.find_all("span",{"class":"b3 regularText aar-title dl-item-name"})
#print(name[0].text)
 rating=container.find_all("span",{"class":"blk5 regularText aar-address1"})
#print(rating[0].text)
 rating1=container.find_all("span",{"class":"blk5 regularText aar-address2"})
#print(rating1[0].text)
 for container in containers:
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    print(rating[0].text)
    rating1=container.find_all("span",{"class":"blk5 regularText aar-address2"})
    print(rating1[0].text)
elif(code==32747):
    my_url = "https://www.aaa.com/autorepair/locations/32747?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    #print(len(containers))
    container = containers[0]
    #print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32748):
    my_url = "https://www.aaa.com/autorepair/locations/32748?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32749):
    my_url = "https://www.aaa.com/autorepair/locations/32749?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32750):
    my_url = "https://www.aaa.com/autorepair/locations/32750?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32751):
    my_url = "https://www.aaa.com/autorepair/locations/32751?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32752):
    my_url = "https://www.aaa.com/autorepair/locations/32752?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32753):
    my_url = "https://www.aaa.com/autorepair/locations/32753?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32754):
    my_url = "https://www.aaa.com/autorepair/locations/32754?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32755):
    my_url = "https://www.aaa.com/autorepair/locations/32755?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32756):
    my_url = "https://www.aaa.com/autorepair/locations/32756?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32757):
    my_url = "https://www.aaa.com/autorepair/locations/32757?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32758):
    my_url = "https://www.aaa.com/autorepair/locations/32758?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32759):
    my_url = "https://www.aaa.com/autorepair/locations/32759?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
elif(code==32760):
    my_url = "https://www.aaa.com/autorepair/locations/32760?radius=50&itemcategory=&napalocations="
    uClient = uReq(my_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    containers = page_soup.find_all("div", {"class": "aar-detail-wrapper"})
    # print(len(containers))
    container = containers[0]
    # print(soup.prettify(containers[0]))
    name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
    # print(name[0].text)
    rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
    # print(rating[0].text)
    rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
    # print(rating1[0].text)
    for container in containers:
        name = container.find_all("span", {"class": "b3 regularText aar-title dl-item-name"})
        print(name[0].text)
        rating = container.find_all("span", {"class": "blk5 regularText aar-address1"})
        print(rating[0].text)
        rating1 = container.find_all("span", {"class": "blk5 regularText aar-address2"})
        print(rating1[0].text)
else:
    print("Please Enter Valid Zip Code")
